#!/usr/bin/env bash

line() {
	for (( i=1; i<=$(tput cols); i++ ));
	do
		printf "$1";
	done;
}

clear
line =
echo "Hi There !"
echo "This script helps in skipping videos while downloading a playlist"
echo "and ofcourse download the rest ;)"
line -

read -p "Give yt link: " link
echo
echo "Checking link..."
echo
cmd="youtube-dl -j --flat-playlist "
$cmd$link | jq -r '.id' | sed 's_^_https://youtu.be/_' > links.log

if $cmd$link &> /dev/null ;then

  echo "All links fetched successfully."
  
  echo "Links are arranged in sequential order remove the ones that you dont need."
  
  read -p "Press Enter to start removing ..."
  line -
  $EDITOR links.log
  youtube-dl -F "$(cat links.log | head -1)" 
  read -p "Choose your format(ex 248+251): " format
  line -
  mkdir -p videos && cd videos
  while read link; do
    $cmd$link | jq '.title'
    printf "\n"
    youtube-dl -f $format $link
    line -
  done < ../links.log

  if [ $? ] ; then
    echo "All videos downloaded successfully."
    cd ..
  fi
else
  echo "Errors encountered !"
fi
line =

#Credits 
#https://superuser.com/questions/1341684/youtube-dl-how-download-only-the-playlist-not-the-files-therein
